#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        $HOME/.config/i3/lock.sh
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

#Put this in /usr/local/bin/
#sudo cp ./i3exit /usr/local/bin/i3exit
