#!/bin/sh

case "$1" in
    lock)
        #$HOME/.config/i3/lock.sh
        betterlockscreen -l blur
        #dm-tool lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        #dm-tool lock
        #betterlockscreen -s
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
#Put this in /usr/local/bin/
#sudo cp ./i3exit /usr/local/bin/i3exit

