#!/bin/sh

FILETYPE=$(xdg-mime query filetype "$1")
APP=$(find /usr/share -type f -name "*.desktop" -printf "%p\n" 2>/dev/null | rofi -threads 0 -dmenu -i -p "select default app" 2>/dev/null)
APP=$(basename -- $APP)
xdg-mime default "$APP" "$FILETYPE"
echo "$APP set as default application to open $FILETYPE"
