#!/usr/bin/env bash

date_time="$(date +"%H:%M:%S %d/%m/%Y")"

$@
shell_return=$?

body="User: $(whoami)@$(hostname -s)\nCommand: $@\nExit code: $shell_return\n$date_time"

curl -s --header "Access-Token: $PUSHBULLET_ACCESS_TOKEN" -X POST \
    https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' \
    --data-binary '{"type": "note", "title": "Execution Done", "body": "'"$body"'"}' \
    &>/dev/null
